<a href="https://colab.research.google.com/github/hanan333/Sprint1/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#randpm decimal mumber between 1,and 10
a=np.random.uniform(1,10)

In [ ]:
a

6.643311760872883

In [ ]:
a=np.random.uniform(1,10,20)#20 random numbers

In [ ]:
a

array([3.16109314, 9.63450416, 5.10085238, 1.5141228 , 4.67396996,
       6.57318968, 7.34373638, 8.48172684, 6.14920997, 9.71084907,
       5.71109196, 2.32941953, 2.4720267 , 2.07423544, 2.94818322,
       6.28217023, 4.37914415, 7.35931832, 4.45609378, 2.6481512 ])

In [ ]:
#list of 3 numbers between 0,1

In [ ]:
a=np.random.rand(3)

In [ ]:
a

array([0.47848507, 0.48145796, 0.63247133])

In [ ]:
#matrix of 2*3 random numbers between(0,1)

In [ ]:
a =np.random.rand(2,3)

In [ ]:
a

array([[0.71273115, 0.06606376, 0.82768923],
       [0.33940422, 0.33801212, 0.42633264]])

In [3]:
import numpy as np

In [4]:
a=np.random.uniform(1,5,10)

In [5]:
a

array([3.3434746 , 2.3575264 , 4.2846914 , 3.30423282, 2.49494006,
       1.03760051, 4.80558322, 1.74649014, 4.55130148, 3.65976173])

In [7]:
a=np.random.rand(3)
a

array([0.67261713, 0.82898748, 0.57356866])

In [9]:
a=np.random.rand(6,5)
a

array([[0.57214071, 0.21814974, 0.7458712 , 0.31214613, 0.42553964],
       [0.3059371 , 0.89538873, 0.9978864 , 0.60354411, 0.51460474],
       [0.56018211, 0.08468065, 0.34806602, 0.01787428, 0.36708011],
       [0.34899912, 0.10348967, 0.13071797, 0.29544165, 0.84616584],
       [0.26702083, 0.61886268, 0.10652078, 0.62011693, 0.4854622 ],
       [0.57277029, 0.87449302, 0.80393237, 0.30937855, 0.00244928]])

In [10]:
list([list(i)for i in a])

[[np.float64(0.5721407070760272),
  np.float64(0.21814974253206976),
  np.float64(0.7458712048111108),
  np.float64(0.312146134230448),
  np.float64(0.4255396424578174)],
 [np.float64(0.3059371012012432),
  np.float64(0.8953887295893644),
  np.float64(0.9978864012082104),
  np.float64(0.6035441110378931),
  np.float64(0.5146047385293522)],
 [np.float64(0.5601821090913004),
  np.float64(0.08468065440667927),
  np.float64(0.3480660201932384),
  np.float64(0.017874281931737235),
  np.float64(0.3670801064587129)],
 [np.float64(0.3489991205581209),
  np.float64(0.10348966938745219),
  np.float64(0.1307179721765902),
  np.float64(0.2954416514538166),
  np.float64(0.8461658376205582)],
 [np.float64(0.26702082534808014),
  np.float64(0.6188626785653479),
  np.float64(0.10652077621557032),
  np.float64(0.620116929070054),
  np.float64(0.4854622027613734)],
 [np.float64(0.5727702896203524),
  np.float64(0.8744930230856328),
  np.float64(0.8039323654524363),
  np.float64(0.3093785490754184),
  np

In [17]:
AllLst=[]
for j in list([list(i for i in a)]):
  AllLst.extend(j)
AllLst

[array([0.57214071, 0.21814974, 0.7458712 , 0.31214613, 0.42553964]),
 array([0.3059371 , 0.89538873, 0.9978864 , 0.60354411, 0.51460474]),
 array([0.56018211, 0.08468065, 0.34806602, 0.01787428, 0.36708011]),
 array([0.34899912, 0.10348967, 0.13071797, 0.29544165, 0.84616584]),
 array([0.26702083, 0.61886268, 0.10652078, 0.62011693, 0.4854622 ]),
 array([0.57277029, 0.87449302, 0.80393237, 0.30937855, 0.00244928])]

In [18]:
AllLst=[i*1000 for i in AllLst]

In [19]:
AllLst

[array([572.14070708, 218.14974253, 745.87120481, 312.14613423,
        425.53964246]),
 array([305.9371012 , 895.38872959, 997.88640121, 603.54411104,
        514.60473853]),
 array([560.18210909,  84.68065441, 348.06602019,  17.87428193,
        367.08010646]),
 array([348.99912056, 103.48966939, 130.71797218, 295.44165145,
        846.16583762]),
 array([267.02082535, 618.86267857, 106.52077622, 620.11692907,
        485.46220276]),
 array([572.77028962, 874.49302309, 803.93236545, 309.37854908,
          2.44928339])]

In [20]:
#ROUNDING
np.round(15.56)

np.float64(16.0)

In [23]:
#rounding for list
RoundList=[np.round (i)for i in AllLst]
RoundList

[array([572., 218., 746., 312., 426.]),
 array([306., 895., 998., 604., 515.]),
 array([560.,  85., 348.,  18., 367.]),
 array([349., 103., 131., 295., 846.]),
 array([267., 619., 107., 620., 485.]),
 array([573., 874., 804., 309.,   2.])]

In [26]:
#ROUNDING TO TWO DECIMALS
RoundList=[np.round(i,2)for i in AllLst]
RoundList

[array([572.14, 218.15, 745.87, 312.15, 425.54]),
 array([305.94, 895.39, 997.89, 603.54, 514.6 ]),
 array([560.18,  84.68, 348.07,  17.87, 367.08]),
 array([349.  , 103.49, 130.72, 295.44, 846.17]),
 array([267.02, 618.86, 106.52, 620.12, 485.46]),
 array([572.77, 874.49, 803.93, 309.38,   2.45])]

In [27]:
#ROUNDING TO FLOOR
np.floor(15.1)

np.float64(15.0)

In [28]:
np.floor(15.9)

np.float64(15.0)

In [30]:
np.ceil(15.9),np.ceil(15.1)

(np.float64(16.0), np.float64(16.0))